Feature add pki init script
cloudposse/docker-openvpn pull request #3
Opened 2017-03-07 14:11 UTC by goruha

2017-03-08 16:59 UTC, osterman commented on Dockerfile
> +      echo '`GITHUB_TOKEN` required for fetching github-pam-plugin'; \
I don't like that we need to expose a `GITHUB_TOKEN` to download *public* releases. This is a dependency we introduced originally when dealing with private repositories. I wish we didn't need to do it for public repos as it raises the barrier for others to contribute.

2017-03-08 17:00 UTC, osterman commented on Dockerfile
> +      echo '`GITHUB_TOKEN` required for fetching github-pam-plugin'; \
Please deprecate `github-pam` since we're not supporting it and not releasing it.

2017-03-08 17:01 UTC, osterman commented on Dockerfile
> +      echo '`GITHUB_TOKEN` required for fetching openvpn-api'; \
I don't like that we need to expose a `GITHUB_TOKEN` to download *public* releases. This is a dependency we introduced originally when dealing with private repositories. I wish we didn't need to do it for public repos as it raises the barrier for others to contribute.

2017-03-08 17:01 UTC, osterman commented on rootfs/usr/local/bin/ovpn_genconfig
> +#!/bin/bash
Why did we copy this? What changed? Concerned about maintenance.

2017-03-08 17:03 UTC, osterman commented on Dockerfile
> +      echo '`GITHUB_TOKEN` required for fetching openvpn-api'; \
Maybe we can modify `github:download-release` to `github:download-private-release` and `github:download-public-release`

2017-03-08 17:05 UTC, osterman commented on Dockerfile
> +ARG S6_OVERLAY_VER=1.17.2.0
Inconsitently named. Should be `S6_OVERLAY_VERSION`

2017-03-08 17:07 UTC, osterman requested changes
See inline comments

2017-03-08 17:11 UTC, osterman commented on Dockerfile
> +ENV GITHUB_PAM_TEAM=
Deprecate

2017-03-09 05:17 UTC, goruha commented on rootfs/usr/local/bin/ovpn_genconfig
> +#!/bin/bash
Original file does not support OVPN_RENEG_SEC option

2017-03-09 05:23 UTC, goruha commented on rootfs/usr/local/bin/ovpn_genconfig
> +#!/bin/bash
can we just add openvpn docker image releases (push to hub.docker) to software updates channel?

2017-03-09 16:01 UTC, osterman commented on rootfs/usr/local/bin/ovpn_genconfig
> +#!/bin/bash
I don't follow the question....

2017-03-09 16:02 UTC, osterman commented on Dockerfile
> +      echo '`GITHUB_TOKEN` required for fetching openvpn-api'; \
I am also okay with just straight-up curl'ing the public release

2017-03-09 18:58 UTC, goruha commented on Dockerfile
> +      echo '`GITHUB_TOKEN` required for fetching github-pam-plugin'; \
Done

2017-03-09 18:59 UTC, goruha commented on rootfs/usr/local/bin/ovpn_genconfig
> +#!/bin/bash
to get notifications when openvpn image new version release

2017-03-09 18:59 UTC, goruha commented on Dockerfile
> +ARG S6_OVERLAY_VER=1.17.2.0
Done

2017-03-09 19:01 UTC, goruha commented on Dockerfile
> +ENV GITHUB_PAM_TEAM=
Done

2017-03-09 19:47 UTC, goruha commented on Dockerfile
> +      echo '`GITHUB_TOKEN` required for fetching openvpn-api'; \
Done

2017-03-09 19:56 UTC, osterman commented on Dockerfile
> +ARG GITHUB_TOKEN
Deprecate `GITHUB_TOKEN`?

2017-03-09 19:58 UTC, osterman approved these changes
Drop `GITHUB_TOKEN`, then merge

2017-03-09 19:59 UTC, goruha commented on Dockerfile
> +ARG GITHUB_TOKEN
Done

2017-03-09 20:02 UTC, merged